package apps.java.loref;

public enum ReplyPrefix {

	WELCOME_MESSAGE("WELCOME_MESSAGE"), 
	UPTIME_MESSAGE("UPTIME_REPLY"), 
	TORRENTS_LIST("TORRENTS_LIST"), 
	TORRENT_STARTED("TORRENT_STARTED"),
	TORRENT_STOPPED("TORRENT_STOPPED"),
	TORRENT_REMOVED("TORRENT_REMOVED"),
	TORRENT_ADDED("TORRENT_ADDED"),
	FREE_SPACE_REPLY("FREE_SPACE"),
	COMMAND_RESPONSE("%%%_command_reply___%%%"), 
	DIRECTORY_CONTENT_RESPONSE("DIRECTORY_CONTENT"), 
	HOMEDIR_RESPONSE("HOME_DIRECTORY"), 
	NOTIFICATION("%%%_notification____%%%"), 
	I_AM_ONLINE("%%%_i_am_online_____%%%"),
	ZONEMINDER_DATA_UPDATED("ZONEMINDER_DATA_UPDATED"),
	FILE_READY_FOR_DOWNLOAD("FILE_READY_FOR_DOWNLOAD"),
	SSH_SHELL_READY("SSH_SHELL_READY"),
<<<<<<< HEAD
	SSH_SHELL_CLOSED("SSH_SHELL_CLOSED")
=======
	SSH_SHELL_CLOSED("SSH_SHELL_CLOSED"),
	REMOTE_CURRENT_TIME("REMOTE_CURRENT_TIME"),
	UNRECOGNIZED_COMMAND("UNRECOGNIZED_COMMAND"),
	FRAME_IMAGE_DATA("FRAME_IMAGE_DATA")
>>>>>>> branch 'master' of https://github.com/lorenzofailla/Domotic.git
	;
		
	private String prefix;

	ReplyPrefix(String prefix) {
        this.prefix = prefix;
    }

    public String prefix() {
        return prefix;
    }

}
